use anyhow::{Context, Result};
use regex::Regex;
use std::collections::HashMap;
use std::fs;
use std::path::Path;
use indicatif::{ProgressBar, ProgressStyle};
use chrono::Utc;

/// FFI 函数信息
#[derive(Debug, Clone)]
pub struct FFIFunction {
    pub name: String,
    pub params: Vec<ParamInfo>,
    pub return_type: String,
}

#[derive(Debug, Clone)]
pub struct ParamInfo {
    pub name: String,
    pub param_type: String,
}

/// 解析 TypeScript 文件提取 FFI 函数声明
pub fn parse_ffi_declarations(files: &[String]) -> Result<Vec<FFIFunction>> {
    let mut functions = Vec::new();
    
    // 正则表达式匹配 declare function
    let re = Regex::new(
        r#"declare\s+function\s+(\w+)\s*\(([^)]*)\)\s*:\s*(\w+)"#
    ).context("Failed to compile regex")?;
    
    for file in files {
        let content = fs::read_to_string(file)
            .context(format!("Failed to read file: {}", file))?;
        
        for cap in re.captures_iter(&content) {
            let name = cap[1].to_string();
            let params_str = &cap[2];
            let return_type = cap[3].to_string();
            
            // 解析参数
            let params = if params_str.trim().is_empty() {
                Vec::new()
            } else {
                params_str
                    .split(',')
                    .filter_map(|p| {
                        let parts: Vec<&str> = p.trim().split(':').collect();
                        if parts.len() == 2 {
                            Some(ParamInfo {
                                name: parts[0].trim().to_string(),
                                param_type: parts[1].trim().to_string(),
                            })
                        } else {
                            None
                        }
                    })
                    .collect()
            };
            
            functions.push(FFIFunction {
                name,
                params,
                return_type,
            });
        }
    }
    
    Ok(functions)
}

/// 按插件分组（根据函数名前缀）
pub fn group_by_plugin(functions: &[FFIFunction]) -> HashMap<String, Vec<FFIFunction>> {
    let mut groups: HashMap<String, Vec<FFIFunction>> = HashMap::new();
    
    for func in functions {
        // 提取插件名：第一个下划线前的部分
        let plugin_name = if let Some(pos) = func.name.find('_') {
            func.name[..pos].to_string()
        } else {
            // 如果没有下划线，使用 "default"
            "default".to_string()
        };
        
        groups.entry(plugin_name).or_insert_with(Vec::new).push(func.clone());
    }
    
    groups
}

/// 生成插件文件
pub fn generate_plugin(plugin_name: &str, functions: &[FFIFunction], output_dir: &str) -> Result<()> {
    let plugin_dir = format!("{}/tsnp/{}", output_dir, plugin_name);
    fs::create_dir_all(&plugin_dir)?;
    
    let total_steps = 7; // 7 个文件
    let pb = ProgressBar::new(total_steps);
    pb.set_style(ProgressStyle::default_bar()
        .template("{spinner:.green} [{elapsed_precise}] [{bar:40.cyan/blue}] {pos}/{len} {msg}")
        .unwrap()
        .progress_chars("#>-"));
    
    pb.set_message(format!("Generating {}", plugin_name));
    
    // 1. 生成 C 文件（win/linux/macos）
    generate_c_file(&plugin_dir, plugin_name, functions, "win")?;
    pb.inc(1);
    pb.set_message(format!("  ✓ {}_win.c", plugin_name));
    
    generate_c_file(&plugin_dir, plugin_name, functions, "linux")?;
    pb.inc(1);
    pb.set_message(format!("  ✓ {}_linux.c", plugin_name));
    
    generate_c_file(&plugin_dir, plugin_name, functions, "macos")?;
    pb.inc(1);
    pb.set_message(format!("  ✓ {}_macos.c", plugin_name));
    
    // 2. 生成配置文件
    generate_main_toml(&plugin_dir, plugin_name, functions)?;
    pb.inc(1);
    pb.set_message("  ✓ ts-native.toml");
    
    generate_platform_toml(&plugin_dir, plugin_name, functions, "win")?;
    pb.inc(1);
    pb.set_message("  ✓ ts-native-win.toml");
    
    generate_platform_toml(&plugin_dir, plugin_name, functions, "linux")?;
    pb.inc(1);
    pb.set_message("  ✓ ts-native-linux.toml");
    
    generate_platform_toml(&plugin_dir, plugin_name, functions, "macos")?;
    pb.inc(1);
    pb.set_message("  ✓ ts-native-macos.toml");
    
    pb.finish_with_message(format!("✅ Plugin '{}' generated", plugin_name));
    
    Ok(())
}

/// 生成 C 实现文件
fn generate_c_file(plugin_dir: &str, plugin_name: &str, functions: &[FFIFunction], platform: &str) -> Result<()> {
    let file_name = format!("{}_{}.c", plugin_name.replace("-", "_"), platform);
    let file_path = format!("{}/{}", plugin_dir, file_name);
    
    let mut content = format!(
        "// {} Implementation for {}\n\
         // Auto-generated by cargo tsn prepare\n\
         // TODO: Implement your platform-specific functions here\n\n",
        get_platform_name(platform),
        plugin_name
    );
    
    if platform == "win" {
        content.push_str("#include <windows.h>\n\n");
    }
    
    content.push_str("// Runtime external functions\n");
    content.push_str("extern double js_string_new(const char* data, unsigned int len);\n");
    content.push_str("extern const char* js_string_unpack(double val);\n");
    content.push_str("extern double js_number_new(double val);\n");
    content.push_str("extern double js_boolean_new(int val);\n\n");
    
    // 生成函数实现
    for func in functions {
        content.push_str(&generate_function_impl(func));
        content.push_str("\n");
    }
    
    fs::write(&file_path, content)?;
    Ok(())
}

/// 生成单个函数的 C 实现
fn generate_function_impl(func: &FFIFunction) -> String {
    let mut impl_str = String::new();
    
    // 函数签名 - 所有参数都是 double 类型
    let param_decls: Vec<String> = (0..func.params.len())
        .map(|i| format!("double p{}", i))
        .collect();
    
    impl_str.push_str(&format!("double {}({}) {{\n", func.name, param_decls.join(", ")));
    
    // 参数解包
    for (i, param) in func.params.iter().enumerate() {
        let param_name = format!("p{}", i);
        let local_name = param.name.clone();
        
        match param.param_type.as_str() {
            "string" => {
                impl_str.push_str(&format!(
                    "    const char* {} = js_string_unpack({});\n",
                    local_name, param_name
                ));
            }
            "number" => {
                impl_str.push_str(&format!(
                    "    double {} = {};\n",
                    local_name, param_name
                ));
            }
            "boolean" => {
                impl_str.push_str(&format!(
                    "    int {} = (int){};\n",
                    local_name, param_name
                ));
            }
            _ => {
                impl_str.push_str(&format!(
                    "    // TODO: Unpack parameter '{}' of type '{}'\n",
                    local_name, param.param_type
                ));
            }
        }
    }
    
    impl_str.push_str("\n");
    impl_str.push_str("    // TODO: Implement your logic here\n");
    impl_str.push_str("\n");
    
    // 返回值打包
    match func.return_type.as_str() {
        "string" => {
            impl_str.push_str("    const char* result = \"\";\n");
            impl_str.push_str("    unsigned int len = 0;\n");
            impl_str.push_str("    return js_string_new(result, len);\n");
        }
        "number" => {
            impl_str.push_str("    double result = 0.0;\n");
            impl_str.push_str("    return js_number_new(result);\n");
        }
        "boolean" => {
            impl_str.push_str("    int result = 0;\n");
            impl_str.push_str("    return js_boolean_new(result);\n");
        }
        "void" => {
            impl_str.push_str("    return 0;\n");
        }
        _ => {
            impl_str.push_str(&format!(
                "    // TODO: Pack return value of type '{}'\n",
                func.return_type
            ));
            impl_str.push_str("    return 0;\n");
        }
    }
    
    impl_str.push_str("}\n");
    
    impl_str
}

/// 生成主配置文件
fn generate_main_toml(plugin_dir: &str, plugin_name: &str, functions: &[FFIFunction]) -> Result<()> {
    let file_path = format!("{}/ts-native.toml", plugin_dir);
    
    // 使用时间戳作为优先级
    let timestamp = Utc::now().timestamp();
    
    let mut content = format!(
        "# ts-native Plugin Configuration\n\
         # Auto-generated by cargo tsn prepare\n\
         # Plugin: {}\n\n\
         [package]\n\
         name = \"tsnp-{}\"\n\
         version = \"0.1.0\"\n\
         priority = {}\n\n",
        plugin_name, plugin_name, timestamp
    );
    
    content.push_str("[includes]\n");
    content.push_str("win = \"ts-native-win.toml\"\n");
    content.push_str("linux = \"ts-native-linux.toml\"\n");
    content.push_str("macos = \"ts-native-macos.toml\"\n\n");
    
    content.push_str("[signatures]\n");
    for func in functions {
        let params: Vec<String> = func.params.iter()
            .map(|p| format!("{}: {}", p.name, p.param_type))
            .collect();
        
        content.push_str(&format!(
            "\"{}\" = \"function({}): {}\"\n",
            func.name,
            params.join(", "),
            func.return_type
        ));
    }
    
    content.push_str("\n[build]\n");
    content.push_str("warn_on_missing = true\n");
    content.push_str("error_on_mismatch = true\n");
    
    fs::write(&file_path, content)?;
    Ok(())
}

/// 生成平台配置文件
fn generate_platform_toml(
    plugin_dir: &str,
    plugin_name: &str,
    functions: &[FFIFunction],
    platform: &str
) -> Result<()> {
    let file_path = format!("{}/ts-native-{}.toml", plugin_dir, platform);
    
    let (os_name, arch) = match platform {
        "win" => ("Windows", vec!["x86_64", "arm64"]),
        "linux" => ("Linux", vec!["x86_64", "arm64"]),
        "macos" => ("macOS", vec!["x86_64", "arm64"]),
        _ => ("Unknown", vec!["x86_64"]),
    };
    
    let arch_str = arch.iter()
        .map(|a| format!("\"{}\"", a))
        .collect::<Vec<_>>()
        .join(", ");
    
    let mut content = format!(
        "# {} Platform Configuration\n\
         # Auto-generated by cargo tsn prepare for plugin '{}'\n\n\
         [platform]\n\
         name = \"{}\"\n\
         os = \"{}\"\n\
         arch = [{}]\n\
         description = \"{} platform\"\n\n",
        os_name,
        plugin_name,
        os_name,
        platform,
        arch_str,
        os_name
    );
    
    content.push_str("[libs.default]\n");
    content.push_str("description = \"Default library\"\n");
    content.push_str("required = true\n\n");
    
    content.push_str("[libs.default.functions]\n");
    for func in functions {
        let c_func_name = func.name.clone();
        let system = if platform == "win" { "SystemAPI" } else { "POSIX" };
        
        let args: Vec<String> = func.params.iter()
            .map(|p| format!("\"{}\"", p.param_type))
            .collect();
        
        content.push_str(&format!(
            "\"{}\" = {{\n",
            func.name
        ));
        content.push_str(&format!("    impl_name = \"{}\",\n", c_func_name));
        content.push_str("    enabled = true,\n");
        content.push_str(&format!("    system = \"{}\",\n", system));
        content.push_str(&format!("    args = [{}],\n", args.join(", ")));
        content.push_str(&format!("    ret = \"{}\",\n", func.return_type));
        content.push_str("    description = \"TODO: Add description\"\n");
        content.push_str("}\n\n");
    }
    
    fs::write(&file_path, content)?;
    Ok(())
}

/// 获取平台名称
fn get_platform_name(platform: &str) -> &'static str {
    match platform {
        "win" => "Windows",
        "linux" => "Linux",
        "macos" => "macOS",
        _ => "Unknown",
    }
}

/// 查找 TypeScript 文件
pub fn find_ts_files(dir: &str) -> Result<Vec<String>> {
    let mut files = Vec::new();
    
    if Path::new(dir).exists() {
        for entry in fs::read_dir(dir)? {
            let entry = entry?;
            let path = entry.path();
            
            if path.is_file() {
                if let Some(ext) = path.extension() {
                    if ext == "ts" {
                        if let Some(path_str) = path.to_str() {
                            files.push(path_str.to_string());
                        }
                    }
                }
            }
        }
    }
    
    Ok(files)
}

/// prepare 命令主入口
pub fn cmd_prepare(input: Option<&str>, output: &str) -> Result<()> {
    println!("📦 Analyzing TypeScript files...");
    
    // 1. 查找 TS 文件
    let ts_files = if let Some(file) = input {
        vec![file.to_string()]
    } else {
        find_ts_files(".")?
    };
    
    if ts_files.is_empty() {
        anyhow::bail!("No TypeScript files found in current directory");
    }
    
    println!("  ✓ Found: {}", ts_files.join(", "));
    
    // 2. 解析 FFI 函数
    let functions = parse_ffi_declarations(&ts_files)?;
    
    if functions.is_empty() {
        anyhow::bail!("No FFI function declarations found");
    }
    
    println!("  ✓ Parsed {} FFI functions", functions.len());
    
    // 3. 按插件分组
    println!("\n🔍 Grouping functions by plugin...");
    let groups = group_by_plugin(&functions);
    
    for (plugin, funcs) in &groups {
        println!("  ✓ {}: {} function(s)", plugin, funcs.len());
    }
    
    // 4. 生成插件文件
    println!("\n⚙️  Generating plugins...\n");
    
    for (plugin_name, funcs) in &groups {
        generate_plugin(plugin_name, funcs, output)?;
        println!();
    }
    
    println!("✅ Prepared {} plugin(s) with {} function(s)", groups.len(), functions.len());
    
    Ok(())
}
